/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;

import PaqueteDatos.TableInformation;
import java.util.ArrayList;

/**
 *
 * @author kejor
 */
public class AddMenu extends javax.swing.JFrame {

    /**
     * Creates new form AddMenu
     */
    public AddMenu() {
        initComponents();
        this.setLocationRelativeTo(null);//para centrar la pantalla
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAddMenu = new javax.swing.JPanel();
        CrearEsquema = new javax.swing.JButton();
        EditarColumnas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CrearEsquema.setText("Crear otro Esquema");
        CrearEsquema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEsquemaActionPerformed(evt);
            }
        });

        EditarColumnas.setText("Agregar otra fila");
        EditarColumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarColumnasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAddMenuLayout = new javax.swing.GroupLayout(PanelAddMenu);
        PanelAddMenu.setLayout(PanelAddMenuLayout);
        PanelAddMenuLayout.setHorizontalGroup(
            PanelAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearEsquema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(EditarColumnas)
                .addContainerGap())
        );
        PanelAddMenuLayout.setVerticalGroup(
            PanelAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(PanelAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearEsquema)
                    .addComponent(EditarColumnas))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAddMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearEsquemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEsquemaActionPerformed
        new NewCreacion().setVisible(true);
        dispose();
    }//GEN-LAST:event_CrearEsquemaActionPerformed

    private void EditarColumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarColumnasActionPerformed
        TableInformation tb = TableInformation.getInstanceSingletonTableInformation();
        System.out.println("Impresion tb: "+tb.getFilas());
        //new Editar1().setVisible(true);
        dispose();
    }//GEN-LAST:event_EditarColumnasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearEsquema;
    private javax.swing.JButton EditarColumnas;
    private javax.swing.JPanel PanelAddMenu;
    // End of variables declaration//GEN-END:variables
}
