/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente;
import PaqueteDatos.DatoFila;
import PaqueteDatos.Fila;
import PaqueteDatos.TableInformation;
import java.awt.event.ActionListener;

/**
 *
 * @author Kevin Rodríguez
 * Este jFrame es donde se le aagrega información a las columnas.
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
public class Editar1 extends javax.swing.JFrame {
    ArrayList<List> Filas;
    ArrayList<String> FilasTemp;
    TableInformation tb;
    int i = 1;
    /**
     * Creates new form Editar1
     */
    public Editar1() {
        Filas= new ArrayList<>();
        FilasTemp = new ArrayList<>();
        initComponents();
        this.setLocationRelativeTo(null);//para centrar la pantalla
        tb = TableInformation.getInstanceSingletonTableInformation();
        //jTextArea1.setText(tb.getNombredecolumnas());
        ArrayList li = new ArrayList<>();
        li = tb.getNombredecolumnas();
        String Co = "";
        for (int ind =0 ; ind<li.size();ind++) {
            Co += li.get(ind)+"\n";
            
        }
        jTextArea1.setText(Co);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEditar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EditText = new javax.swing.JTextPane();
        Crear = new javax.swing.JButton();
        CrearEsquemaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(EditText);

        Crear.setText("Crear");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        CrearEsquemaButton.setText("Crear Esquema");
        CrearEsquemaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearEsquemaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEditarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(CrearEsquemaButton))
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(Add)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Add)
                        .addGap(91, 91, 91)
                        .addComponent(Crear)
                        .addGap(46, 46, 46)
                        .addComponent(CrearEsquemaButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
                
        //System.out.println("Ingresado:"+EditText.getText());
        FilasTemp.add(EditText.getText());
        EditText.setText("");
        
    }//GEN-LAST:event_AddActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        
        FilasTemp.add(0,""+i);
        System.out.println(FilasTemp);
        Filas.add(FilasTemp);
        tb.setFilas(Filas);
        System.out.println("tb: "+tb.getFilas());
        //Fila datos= new Fila(Filas);
        System.out.println("Ingresado:"+Filas);
        //DatoFila datoFila= new DatoFila(datos);
        EditText.setText("");
        FilasTemp = new ArrayList<>();
        //new AddMenu().setVisible(true);
        i++;
    }//GEN-LAST:event_CrearActionPerformed

    private void CrearEsquemaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearEsquemaButtonActionPerformed
        // TODO add your handling code here:
        tb.getNombredecolumnas().add(0,"Ídice");
        Tabla test= new Tabla(tb.getNombre(),tb.getNombredecolumnas(),tb.getFilas());
        new Menu_Esquemas().setVisible(true);
        dispose();
    }//GEN-LAST:event_CrearEsquemaButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Crear;
    private javax.swing.JButton CrearEsquemaButton;
    private javax.swing.JTextPane EditText;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
